export const API_URL_RESTART = '/restart'
export const API_URL_START   = '/start'
export const API_URL_STOP    = '/stop'
export const API_URL_UPDATE  = '/update'
export const API_URL_REMOVE  = '/remove'
export const API_URL_PULL    = '/pull'
export const API_URL_STATUS  = '/status'
